# Generated by Django 4.1.1 on 2022-09-12 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='subscription_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
